# Generated by Django 3.1.4 on 2021-03-24 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='task_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task/')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('pincode', models.CharField(max_length=7)),
                ('mobile_number', models.IntegerField()),
                ('proof', models.FileField(upload_to='task/proof/')),
                ('document', models.FileField(upload_to='task/document/')),
                ('deadline', models.CharField(max_length=7)),
                ('note', models.CharField(max_length=1000)),
                ('Gmaplink', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='temp_task_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task/')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('pincode', models.CharField(max_length=7)),
                ('mobile_number', models.IntegerField()),
                ('proof', models.FileField(upload_to='task/proof/')),
                ('document', models.FileField(upload_to='task/document/')),
                ('deadline', models.CharField(max_length=7)),
                ('note', models.CharField(max_length=1000)),
                ('Gmaplink', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='task_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_detail_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task_detail')),
            ],
        ),
        migrations.CreateModel(
            name='payment_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_payment', models.CharField(max_length=100)),
                ('agent_payment', models.CharField(max_length=100)),
                ('user_payment_status', models.CharField(choices=[(0, 0), (1, 1)], default=0, max_length=1)),
                ('agent_payment_status', models.CharField(choices=[(0, 0), (1, 1)], default=0, max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('task_detail_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='panding_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 0), (1, 1)], default=0, max_length=1)),
                ('accept_time', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('panding_task_agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='panding_task_agent', to=settings.AUTH_USER_MODEL)),
                ('panding_task_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panding_task_user', to=settings.AUTH_USER_MODEL)),
                ('task_detail_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task_detail')),
            ],
        ),
        migrations.CreateModel(
            name='exntend_user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('mobile_number', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=1000)),
                ('pincode', models.CharField(max_length=7)),
                ('xender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('role', models.CharField(choices=[(0, 0), (1, 1)], default=0, max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='completed_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 0), (1, 1)], default=1, max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('completed_task_agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='completed_task_agent', to=settings.AUTH_USER_MODEL)),
                ('completed_task_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_task_user', to=settings.AUTH_USER_MODEL)),
                ('task_detail_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task_detail')),
            ],
        ),
    ]
