# Generated by Django 3.1.4 on 2021-03-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_task_detail',
        ),
    ]
