# Generated by Django 3.1.4 on 2021-03-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210324_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panding_task',
            name='accept_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='task/document/'),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task/'),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='task/proof/'),
        ),
    ]
