# Generated by Django 3.1.4 on 2021-03-24 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210324_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panding_task',
            name='panding_task_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='panding_task_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
