# Generated by Django 3.1.4 on 2021-03-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210324_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='panding_task',
            name='otp',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
