# Generated by Django 3.1.4 on 2021-03-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_panding_task_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_task',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.payment_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panding_task',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.payment_info'),
            preserve_default=False,
        ),
    ]
