# Generated by Django 3.1.4 on 2021-03-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210325_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_detail',
            old_name='Gmaplink',
            new_name='gmaplink',
        ),
    ]
