# Generated by Django 3.1.4 on 2021-03-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210325_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panding_task',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
