# Generated by Django 3.1.4 on 2021-03-26 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20210325_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_task',
            name='completed_task_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='completed_task_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
