# Generated by Django 3.1.4 on 2021-03-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210326_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_task',
            name='refund_status',
            field=models.CharField(choices=[('-', '-'), ('panding', 'panding'), ('success', 'success')], default='-', max_length=8),
        ),
    ]
