# Generated by Django 3.1.4 on 2021-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_completed_task_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exntend_user_details',
            name='channel_name',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
