# Generated by Django 3.1.4 on 2021-03-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210327_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='exntend_user_details',
            name='user_channel_name',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
