# Generated by Django 3.1.4 on 2021-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210327_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='socket_name',
            field=models.CharField(default='adsa', max_length=100),
            preserve_default=False,
        ),
    ]
