# Generated by Django 3.1.4 on 2021-03-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_online_socket_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='online',
        ),
    ]
