# Generated by Django 3.1.4 on 2021-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210331_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exntend_user_details',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exntend_user_details',
            name='image',
            field=models.ImageField(upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='exntend_user_details',
            name='mobile_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='exntend_user_details',
            name='pincode',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='exntend_user_details',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('agent', 'agent')], default='user', max_length=6),
        ),
        migrations.AlterField(
            model_name='exntend_user_details',
            name='xender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
