# Generated by Django 3.1.4 on 2021-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210401_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='panding_task',
            name='agent_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
