# Generated by Django 3.1.4 on 2021-04-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_panding_task_agent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exntend_user_details',
            name='image',
            field=models.ImageField(blank=True, default='profile/defaultprofile.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='image',
            field=models.ImageField(blank=True, default='profile/defaultprofile.png', null=True, upload_to='task/'),
        ),
    ]
