# Generated by Django 3.1.4 on 2021-04-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210413_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_info',
            name='user_bankname',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='user_banktxnid',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='user_gatewayname',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='user_orderid',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='user_paymentmode',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='user_txndate',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='user_txnid',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='completed_task',
            name='task_detail_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.task_detail'),
        ),
        migrations.AlterField(
            model_name='panding_task',
            name='task_detail_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.task_detail'),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='task_detail_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.task_detail'),
        ),
    ]
