# Generated by Django 3.1.4 on 2021-05-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210416_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=2000)),
                ('reply_message', models.CharField(max_length=2000)),
            ],
        ),
    ]
