# Generated by Django 3.1.4 on 2021-05-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='reply_message',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
