# Generated by Django 3.1.4 on 2021-05-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210503_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_detail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
