# Generated by Django 3.1.4 on 2021-05-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_task_detail_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_task',
            name='accept_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed_task',
            name='accepted',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=10),
        ),
        migrations.AlterField(
            model_name='completed_task',
            name='refund_status',
            field=models.CharField(choices=[('-', '-'), ('panding', 'panding')], default='-', max_length=8),
        ),
    ]
