# Generated by Django 3.1.4 on 2021-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210510_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_task',
            name='refund_status',
            field=models.CharField(choices=[('-', '-'), ('panding', 'panding')], default='-', max_length=8),
        ),
    ]
