# Generated by Django 3.1.4 on 2021-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210510_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_task',
            name='task_expire_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
