# Generated by Django 3.1.4 on 2021-05-11 10:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20210510_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='refund_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.IntegerField()),
                ('refund_id', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 11, 10, 55, 32, 630641, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exntend_user_details',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 11, 10, 55, 32, 630641, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='online',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 11, 10, 55, 32, 630641, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task_notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 11, 10, 55, 32, 630641, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completed_task',
            name='refund_status',
            field=models.CharField(choices=[('-', '-'), ('panding', 'panding')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='completed_task',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='expired', max_length=20),
        ),
        migrations.AddField(
            model_name='completed_task',
            name='refund_detail',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_detail', to='main.refund_detail'),
        ),
    ]
