# Generated by Django 3.1.4 on 2021-05-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210511_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund_detail',
            name='refund_status',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('panding', 'panding')], default='panding', max_length=20),
        ),
    ]
