# Generated by Django 3.1.4 on 2021-05-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_refund_detail_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='panding_task',
            name='otp_cancel',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
