# Generated by Django 3.1.4 on 2021-05-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_panding_task_otp_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='agent_payment_status',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('panding', 'panding')], default='fail', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='user_payment_status',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('panding', 'panding')], default='fail', max_length=8),
        ),
    ]
