# Generated by Django 3.1.4 on 2021-05-22 07:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0046_auto_20210517_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exntend_user_details',
            new_name='extended_user_details',
        ),
    ]
