# Generated by Django 3.1.4 on 2021-05-22 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0047_auto_20210522_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='pending_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initilize', 'initilize'), ('accepted', 'accepted')], default='initilize', max_length=10)),
                ('accept_time', models.DateTimeField(blank=True, null=True)),
                ('agent_location', models.CharField(blank=True, max_length=500, null=True)),
                ('otp', models.CharField(blank=True, max_length=7, null=True)),
                ('otp_cancel', models.CharField(blank=True, max_length=7, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('task_expire_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='completed_task',
            name='refund_status',
            field=models.CharField(choices=[('-', '-'), ('pending', 'pending')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='agent_payment_status',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('pending', 'pending')], default='fail', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='user_payment_status',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('pending', 'pending')], default='fail', max_length=8),
        ),
        migrations.AlterField(
            model_name='refund_detail',
            name='refund_status',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='panding_task',
        ),
        migrations.AddField(
            model_name='pending_task',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.payment_info'),
        ),
        migrations.AddField(
            model_name='pending_task',
            name='pending_task_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pending_task_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pending_task',
            name='pending_task_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_task_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pending_task',
            name='task_detail_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.task_detail'),
        ),
    ]
